window.actionTypes = {
  INCREMENT_DAY: 'INCREMENT_DAY',
  CHANGE_CURRENT_TURN: 'CHANGE_CURRENT_TURN',
  GENERATE_INCOME: 'GENERATE_INCOME',
  
  SELECT_UNIT: 'SELECT_UNIT',
  MOVE_UNIT: 'MOVE_UNIT',
  FIRE_ON_UNIT: 'FIRE_ON_UNIT',
  DECREMENT_AMMO: 'DECREMENT_AMMO',
  DECREMENT_FUEL: 'DECREMENT_FUEL',
  CAPTURE_PROPERTY: 'CAPTURE_PROPERTY',
  BUILD_UNIT: 'BUILD_UNIT',
  JOIN_UNITS: 'JOIN_UNITS'
};